### ISSUE TITLE
How am I supposed to do "fade-in" animations? 

### ISSUE THREAD

**Issue by rasteiner** [pocketjoso/penthouse#122]
penthouse strips away all `@keyframes` declarations. This is, it seems, [by design](https://github.com/pocketjoso/penthouse/issues/34#issuecomment-60353050). 

Now I'd like to have a fade-in animation, on page load, for an item above the fold. Assume something like this:

```css
.thing {
   animation-name: foo;
   animation-fill-mode: both;
}

@keyframes foo {
   0% {
     opacity: 0;
   }
   100% {
     opacity: 1;
   }
}
```

Not having the animation in the critical css means I first see the `.thing` and then, after that 150ms loading time the animation begins by having the `.thing` abruptly disappear and then fade-in. 

Of course I could set an `opacity: 0` in the selector, but that would mean giving up on progressive enhancement (if the browser doesn't support animations the `.thing` remains hidden).

How should we deal with such situations? 

PS: of course in this simple case I could get away with transitions, but this isn't the point.

**Comment by pocketjoso** [comment]
Hi,
You're right that `Penthouse` strips away all `@keyframe`s, and it also strips away all `animation` attributes. This is as you say by design, as the majority of animations are not needed for the first render. However I have not thought of your use case before. Perhaps Penthouse can be smarter about what animations and keyframes to leave in there, as they are used on load.

Until I have a solution for that though, your best option is to either use the `opacity` trick, or manually appending the "missing" css (both the stripped out `animation` rules, and the `@keyframe`) to the critical css that `Penthouse` returns.

I will take a look at this during the next weekend.

**Comment by rasteiner** [comment]
Thanks for the response =)

At the moment I just factored out the animation stuff I need on load and included them manually, like you suggested.  

I guess most people would also be happy to "simply" annotate (like with a comment) the animations they want to preserve in critical css. Something like this:

```css
.thing {
   /*penthouse:preserve_animation*/
   animation-name: foo;
   animation-fill-mode: both;
}

@keyframes foo {
   0% {
     opacity: 0;
   }
   100% {
     opacity: 1;
   }
}
```

I mean if it could figure out automatically which animations to keep it would be awesome, but since I don't even have a clou how this could be achieved, I just wanted to point a "cheaper" option.
