### ISSUE TITLE
Penthouse already optimized css

### ISSUE THREAD

**Issue by hummal** [pocketjoso/penthouse#191]
When I have an CSS String like that:
```css
@media all and (min-width:1024px){.test{content:"MQ .test1"}.test{content:"MQ .test2"}}
```
Penthouse will combine the 2 .test classes to one. This could lead to an problem where I want the second selector to overwrite the first one. 

Maybe Iam wrong but as I remember when we had phantomjs as browser emulation we penthouse didn't respond with minimized css.
Even CSS processors like postcss give me the option to decide if I want to combine duplicate selectors or not. Maybe that should be included here aswell.

**Comment by pocketjoso** [comment]
Hi @hummal. There's no minification built in into Penthouse, but the normalisation step that is used for invalid css input might collapse rules (via Chrome). To avoid this, run penthouse the `strict: true`, causing it to bail on css errors instead.

You could also paste your css into the css tabs here:
https://astexplorer.net/

And see what errors that shows. After you've fixed the errors, try again and see if rules are no longer collapsed.

-------------

Finally, any program that minifies css and collapses rules will preserve the original order and specificity. They will never change your css in away that leads to a different result in the browser.

**Comment by hummal** [comment]
Checked the CSS. Strict is already true. astexplorer had nothing to complain. Result is still combined:
```css
@media (min-width: 1024px) {
    .test {
        content: "MQ .test1";
        content: "MQ .test2"
    }
```
