### ISSUE TITLE
Dot converted to comma

### ISSUE THREAD

**Issue by ryuran** [pocketjoso/penthouse#194]
Hello

My original css have some float value with css valid dot.
```css
font-size: 62.5%;
```
But penthouse transform this dot to comma
```css
font-size: 62,5%;
```
and the value become invalid

# EDIT:
When `strict: false` and ASTexplorer fail, penthouse run chrome CSS nomalizer then this one convert dots to comma.

## Test case: 
```css
body {
  /* this data URI fail on ASTexplorer*/
  background-image: url("data:image/svg+xml;utf8,%3Csvg%20version='1.1'%20xmlns='http://www.w3.org/2000/svg'%20xmlns:xlink='http://www.w3.org/1999/xlink'%20viewBox='0%200%2010%2010'%3E%3Cstyle%3Epath%7Bfill:%20rgb(0,0,0);%7D%3C/style%3E%3C/svg%3E");
  /* this font-size value is transformed to 62,5% by chrome css normalizer */
  font-size: 62.5%;
}
```
