### ISSUE TITLE
Height param is ignored sometimes

### ISSUE THREAD

**Issue by bezoerb** [pocketjoso/penthouse#280]
There's a weird bug where penthouse/puppeteer ignores the passed height value sometimes. It looks like the result depends on the file location.
I have created a testcase using the latest version of penthouse.
The test uses the same html file copied to different locations.

```js
const penthouse = require('penthouse');
const fs = require('fs-extra');

(async () => {

  const cssString = await fs.readFile('test/fixtures/styles/adaptive.css','utf8');

  const file1 = '/private/var/folders/7w/tcbwbwsx4rg2mkk2l5_1l_9h0000gp/T/14890e18bec27e7df8566c1150724112.html';
  const file2 = '/Users/bzoerb/Github/critical-rewrite/test/fixtures/generate-adaptive.html';
  const file3 = '/Users/bzoerb/test.html';

  const contents1 = await fs.readFile(file1,'utf8');
  const contents2 = await fs.readFile(file2,'utf8');
  const contents3 = await fs.readFile(file3,'utf8');

  console.log('Contents identical?', contents1 == contents2 && contents2 == contents3);
  if (contents1 != contents2 || contents2 !== contents3) {
    console.log(contents1);
    console.log(contents2);
    console.log(contents2);
  } else {
    console.log((contents1))
  }

  const options = {
    cssString,
    width: 1000,
    height: 70,
  };

  console.log({options});

  const result1 = await penthouse({...options, url: `file://${file1}`});
  const result2 = await penthouse({...options, url: `file://${file2}`});
  const result3 = await penthouse({...options, url: `file://${file3}`});


  console.log('Result identical?', result1 == result2 && result2 == result3);
  if (result1 == result2 && result2 == result3) {
    console.log(result1);
  } else {
    console.log(result1);
    console.log(result2);
    console.log(result3);
  }

})();

```

Running the test generates the following output:
```bash
❯ node penthouse-test.js

Contents identical? true

<!doctype html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <title>critical css test</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="styles/adaptive.css">
        </head>
    <body>
        <div id="revenge"></div>
        <div id="of"></div>
        <div id="guybrush"></div>
        <div id="threepwood"></div>
    </body>
</html>

{ options:
   { cssString:
      '@media screen and (min-width: 900px) {\n    div  {\n        height: 400px;\n        background: brown;\n    }\n}\n\n#revenge {\n    background: papayawhip;\n}\n\n#of {\n    background: teal;\n}\n\n#guybrush {\n    color: pink;\n}\n\n#threepwood {\n    background: orange;\n    content: \'monkey island\';\n}\n',
     width: 1000,
     height: 70 } }

Resultidentical? false

@media screen and (min-width:900px){div{height:400px;background:brown}}#revenge{background:papayawhip}#of{background:teal}#guybrush{color:pink}#threepwood{background:orange;content:'monkey island'}
@media screen and (min-width:900px){div{height:400px;background:brown}}#revenge{background:papayawhip}
@media screen and (min-width:900px){div{height:400px;background:brown}}#revenge{background:papayawhip}#of{background:teal}#guybrush{color:pink}#threepwood{background:orange;content:'monkey island'}
```

**fixtures/generate-adaptive.html**
```html
<!doctype html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <title>critical css test</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="styles/adaptive.css">
        </head>
    <body>
        <div id="revenge"></div>
        <div id="of"></div>
        <div id="guybrush"></div>
        <div id="threepwood"></div>
    </body>
</html>
```

**fixtures/styles/adaptive.css**
```css
@media screen and (min-width: 900px) {
    div  {
        height: 400px;
        background: brown;
    }
}

#revenge {
    background: papayawhip;
}

#of {
    background: teal;
}

#guybrush {
    color: pink;
}

#threepwood {
    background: orange;
    content: 'monkey island';
}
```

**Comment by bezoerb** [comment]
@pocketjoso: thanks for all the effort you already put into `penthouse` 👍 
`critical` would not be possible without it ;)

**Comment by pocketjoso** [comment]
Thanks for the comprehensive bug report - will take a look this weekend and hopefully push a fix out quickly. 👍

**Comment by bezoerb** [comment]
@pocketjoso: thanks for looking into it. I will also try to find something

**Comment by bezoerb** [comment]
@pocketjoso: just looked at the result from your console output and this should be
`@media screen and (min-width:900px){div{height:400px;background:brown}}#revenge{background:papayawhip}`

instead of
`@media screen and (min-width:900px){div{height:400px;background:brown}}#revenge{background:papayawhip}#of{background:teal}#guybrush{color:pink}#threepwood{background:orange;content:'monkey island'}`

The divs **#of**, **#guybrush** and **#threepwood** are not visible on the first view because we only have a height of 70px and the first div already takes 400px.

**Comment by pocketjoso** [comment]
I had missed making sure the css was available at the different paths. With I get the same, correct results:
```
Result identical? true
@media screen and (min-width:900px){div{height:400px;background:brown}}#revenge{background:papayawhip}
```

Are you sure the css is available from the different locations you are testing from @bezoerb?

**Comment by bezoerb** [comment]
The `.../fixtures/generate-adaptive.html` gives me the correct result: 
```css
@media screen and (min-width:900px){div{height:400px;background:brown}}#revenge{background:papayawhip}
```

With every other location the output is wrong:
```css
@media screen and (min-width:900px){div{height:400px;background:brown}}#revenge{background:papayawhip}#of{background:teal}#guybrush{color:pink}#threepwood{background:orange;content:'monkey island'}
```

Maybe this is some sort of caching issue inside puppeteer?
