### ISSUE TITLE
[Q] Is it possible to filter out by css value or apply browserlist?

### ISSUE THREAD

**Issue by aaarichter** [pocketjoso/penthouse#283]
Hello - I have seen the `propertiesToRemove` option, which works great e.g to filter vendor specific properties.

### Question1:

Is there an option to remove properties with certain CSS values? Or can a [browserlist](https://github.com/browserslist/browserslist) configuration be applied?

e.g
```css
.myClass{
  display: -ms-flexbox; // to remove
  display: flex;
}
```

### Question 2:
Is there a way to remove ` !important` from a CSS value?
