### ISSUE TITLE
Output Wrong CSS

### ISSUE THREAD

**Issue by cc2937** [pocketjoso/penthouse#339]
original CSS:

```css
.elem {
  margin: 0 .-18rem;
}
```

output:

```css
.elem{margin: 0.-18rem}
```

expected:
```css
.elem{margin: 0 .-18rem}
```
