### ISSUE TITLE
CSS3 selectors (::selection) result in malformed CSS

### ISSUE THREAD

**Issue by optimalisatie** [pocketjoso/penthouse#36]
CSS3 selectors are causing malformed CSS.

The following source code (part of **all.css**)

```css
::-moz-selection {
  color: #fff;
  background-color: #FE1486
}
::selection {
  color: #fff;
  background-color: #FE1486
}
```

Becomes the following after [grunt-penthouse](https://github.com/pocketjoso/penthouse):

```css
::-moz-selection {
  color: #fff;
  background-color: #FE1486
}
::selection {
  cul{
    list-style: none
  }
  .clear {
    clear: both!important
  }
  footer,header,nav {
    display: block
  }
  :focus {
    outline: 0
  }
  input {
    border: 1px solid #d8d5d5;
    background: #fff;
    padding: 5px
  }
}
```

The element **cul** is unknown (probably malformed code). When the CSS code is minified via cssmin it is further malformed. The bracket of **::selection {** does not have an ending anymore, causing a large part of the CSS file to be removed.
